package com.agentcontrolcenter.desktop.app

/**
 * UI 字符串 — 桌面 v1 支持英语 / 简体中文（对齐移动端四语体系的子集，
 * ja/ko 列入路线图）。
 */
object Strings {
    var locale: String = "en"

    private val en = mapOf(
        "app.title" to "Agent Control Center",
        "nav.chat" to "Chat",
        "nav.agents" to "Agents",
        "nav.settings" to "Settings",
        "chat.new_session" to "New Session",
        "chat.placeholder" to "Message your agent… (Enter to send, Shift+Enter for newline)",
        "chat.send" to "Send",
        "chat.stop" to "Stop",
        "chat.empty" to "No messages yet. Say hello to your agent.",
        "chat.no_session" to "Create or select a session to start",
        "chat.delete_session" to "Delete session",
        "agents.title" to "Agent Configurations",
        "agents.add" to "Add Agent",
        "agents.edit" to "Edit",
        "agents.connect" to "Connect",
        "agents.disconnect" to "Disconnect",
        "agents.connected" to "Connected",
        "agents.disconnected" to "Disconnected",
        "agents.delete" to "Delete",
        "agents.empty" to "No agents configured yet. Add one to start chatting.",
        "agents.name" to "Name",
        "agents.type" to "Type",
        "agents.server_url" to "Server URL",
        "agents.api_key" to "API Key (optional)",
        "agents.model" to "Model",
        "agents.system_prompt" to "System Prompt (optional)",
        "agents.temperature" to "Temperature",
        "agents.max_tokens" to "Max Tokens",
        "agents.save" to "Save",
        "agents.cancel" to "Cancel",
        "settings.title" to "Settings",
        "settings.appearance" to "Appearance",
        "settings.dark_theme" to "Dark theme",
        "settings.language" to "Language",
        "settings.language_en" to "English",
        "settings.language_zh" to "简体中文",
        "settings.security" to "Security",
        "settings.e2e_passphrase" to "E2E passphrase (peer-to-peer, WebSocket only)",
        "settings.e2e_hint" to "Encrypted with AES-256-GCM (AH1: format), interoperable with the mobile clients. Leave empty to disable.",
        "settings.behavior" to "Behavior",
        "settings.close_to_tray" to "Close to system tray instead of quitting",
        "settings.about" to "About",
        "settings.version" to "Desktop 5.2.0 — Compose Multiplatform",
        "settings.open_source" to "Part of the Agent Control Center repo (Android / iOS / HarmonyOS / Desktop)",
        "tray.show" to "Show",
        "tray.quit" to "Quit",
        "status.latency" to "Latency",
        "status.model" to "Model",
        "error.not_connected" to "Not connected — select an agent and press Connect first",
        "error.credential_vault" to "Cannot encrypt the API key — local credential vault unavailable. The agent was not saved.",
        "error.credential_decrypt" to "Some stored API keys could not be decrypted and were cleared. Please re-enter them.",
    )

    private val zh = mapOf(
        "app.title" to "Agent 控制中心",
        "nav.chat" to "聊天",
        "nav.agents" to "Agents",
        "nav.settings" to "设置",
        "chat.new_session" to "新建会话",
        "chat.placeholder" to "给 Agent 发消息…（Enter 发送，Shift+Enter 换行）",
        "chat.send" to "发送",
        "chat.stop" to "停止",
        "chat.empty" to "还没有消息，向你的 Agent 打个招呼吧。",
        "chat.no_session" to "创建或选择一个会话开始对话",
        "chat.delete_session" to "删除会话",
        "agents.title" to "Agent 配置",
        "agents.add" to "添加 Agent",
        "agents.edit" to "编辑",
        "agents.connect" to "连接",
        "agents.disconnect" to "断开",
        "agents.connected" to "已连接",
        "agents.disconnected" to "未连接",
        "agents.delete" to "删除",
        "agents.empty" to "还没有配置 Agent，先添加一个开始对话吧。",
        "agents.name" to "名称",
        "agents.type" to "类型",
        "agents.server_url" to "服务器地址",
        "agents.api_key" to "API Key（可选）",
        "agents.model" to "模型",
        "agents.system_prompt" to "系统提示词（可选）",
        "agents.temperature" to "温度",
        "agents.max_tokens" to "最大 Token 数",
        "agents.save" to "保存",
        "agents.cancel" to "取消",
        "settings.title" to "设置",
        "settings.appearance" to "外观",
        "settings.dark_theme" to "深色主题",
        "settings.language" to "语言",
        "settings.language_en" to "English",
        "settings.language_zh" to "简体中文",
        "settings.security" to "安全",
        "settings.e2e_passphrase" to "E2E 端到端口令（对等模式，仅 WebSocket）",
        "settings.e2e_hint" to "AES-256-GCM 加密（AH1: 格式），与移动端互操作。留空即关闭。",
        "settings.behavior" to "行为",
        "settings.close_to_tray" to "关闭窗口时最小化到托盘",
        "settings.about" to "关于",
        "settings.version" to "桌面版 5.2.0 — Compose Multiplatform",
        "settings.open_source" to "Agent Control Center 仓库组成部分（Android / iOS / HarmonyOS / 桌面）",
        "tray.show" to "显示主窗口",
        "tray.quit" to "退出",
        "status.latency" to "延迟",
        "status.model" to "模型",
        "error.not_connected" to "未连接——请先在 Agents 页选择并连接一个 Agent",
        "error.credential_vault" to "无法加密 API Key——本地凭据保险库不可用，该 Agent 未保存。",
        "error.credential_decrypt" to "部分已存储的 API Key 无法解密，已清空，请重新填写。",
    )

    fun t(key: String): String =
        (if (locale == "zh") zh[key] else null) ?: en[key] ?: key
}
